# Generated by Django 3.2.8 on 2022-04-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userint', '0003_auto_20220329_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='livelink',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='repolink',
        ),
        migrations.AddField(
            model_name='participant',
            name='colablink',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='datasetlink',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
    ]
