# Generated by Django 3.2.8 on 2022-04-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userint', '0004_auto_20220408_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=5000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='participant',
            name='colablink',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='datasetlink',
        ),
        migrations.AddField(
            model_name='participant',
            name='submissionlink',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
    ]
